# Generated by Django 6.0.7 on 2026-07-07 21:09

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0003_teaminvitation'),
        ('projects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CheckInPoint',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=150)),
                ('code', models.CharField(db_index=True, max_length=32, unique=True)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='check_in_points', to='companies.company')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='check_in_points', to='companies.site')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='AttendanceManualMark',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('work_date', models.DateField(db_index=True)),
                ('status', models.CharField(choices=[('not_checked_in', 'Not Checked In'), ('present', 'Present'), ('absent', 'Absent'), ('late', 'Late')], max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_manual_marks', to='companies.company')),
                ('marked_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='marked_attendance_records', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_manual_marks', to='projects.project')),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_manual_marks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-work_date'],
                'unique_together': {('project', 'worker', 'work_date')},
            },
        ),
        migrations.CreateModel(
            name='AttendanceEvent',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('event_type', models.CharField(choices=[('check_in', 'Check In'), ('check_out', 'Check Out'), ('break_start', 'Break Start'), ('break_end', 'Break End')], max_length=16)),
                ('event_at', models.DateTimeField(db_index=True)),
                ('work_date', models.DateField(db_index=True)),
                ('method', models.CharField(choices=[('qr_scan', 'QR Scan'), ('mobile', 'Mobile'), ('manual', 'Manual')], max_length=16)),
                ('is_late', models.BooleanField(default=False)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('notes', models.TextField(blank=True)),
                ('is_offline_sync', models.BooleanField(default=False)),
                ('client_event_id', models.CharField(blank=True, db_index=True, max_length=64)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_events', to='companies.company')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_events', to='projects.project')),
                ('recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recorded_attendance_events', to=settings.AUTH_USER_MODEL)),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_events', to=settings.AUTH_USER_MODEL)),
                ('check_in_point', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attendance_events', to='attendance.checkinpoint')),
            ],
            options={
                'ordering': ['-event_at'],
                'indexes': [models.Index(fields=['project', 'work_date'], name='attendance__project_dd3fc2_idx'), models.Index(fields=['worker', 'work_date'], name='attendance__worker__8018ca_idx')],
            },
        ),
        migrations.CreateModel(
            name='ProjectWorkerAssignment',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('trade', models.CharField(choices=[('mason', 'Mason'), ('electrician', 'Electrician'), ('plumber', 'Plumber'), ('steel_fixer', 'Steel Fixer'), ('carpenter', 'Carpenter'), ('engineer', 'Engineer'), ('foreman', 'Foreman'), ('labourer', 'Labourer'), ('other', 'Other')], default='other', max_length=32)),
                ('employee_code', models.CharField(blank=True, max_length=50)),
                ('shift_start_time', models.TimeField(default='07:00')),
                ('shift_end_time', models.TimeField(default='17:00')),
                ('is_active', models.BooleanField(default=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='worker_assignments', to='companies.company')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='worker_assignments', to='projects.project')),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_assignments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['worker__first_name', 'worker__last_name'],
                'unique_together': {('project', 'worker')},
            },
        ),
    ]
