# Generated by Django 6.0.7 on 2026-07-07 20:56

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0003_teaminvitation'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255)),
                ('code', models.CharField(blank=True, max_length=50)),
                ('project_type', models.CharField(choices=[('residential', 'Residential'), ('commercial', 'Commercial'), ('industrial', 'Industrial'), ('infrastructure', 'Infrastructure'), ('mixed_use', 'Mixed Use'), ('renovation', 'Renovation')], default='residential', max_length=32)),
                ('status', models.CharField(choices=[('planning', 'Planning'), ('active', 'Active'), ('on_hold', 'On Hold'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='planning', max_length=32)),
                ('description', models.TextField(blank=True)),
                ('client_name', models.CharField(blank=True, max_length=255)),
                ('client_email', models.EmailField(blank=True, max_length=254)),
                ('client_phone', models.CharField(blank=True, max_length=20)),
                ('budget_total', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('budget_spent', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('currency', models.CharField(default='KES', max_length=3)),
                ('planned_start_date', models.DateField(blank=True, null=True)),
                ('planned_end_date', models.DateField(blank=True, null=True)),
                ('actual_start_date', models.DateField(blank=True, null=True)),
                ('actual_end_date', models.DateField(blank=True, null=True)),
                ('progress_percent', models.PositiveSmallIntegerField(default=0)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='companies.company')),
                ('project_manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_projects', to=settings.AUTH_USER_MODEL)),
                ('site', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects', to='companies.site')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['company', 'status'], name='projects_pr_company_48dbe1_idx'), models.Index(fields=['company', 'slug'], name='projects_pr_company_ed58f6_idx')],
                'unique_together': {('company', 'code')},
            },
        ),
    ]
