# Generated by Django 6.0.7 on 2026-07-07 21:01

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0003_teaminvitation'),
        ('projects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteDiaryEntry',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('entry_date', models.DateField(db_index=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('approved', 'Approved')], default='draft', max_length=16)),
                ('weather_condition', models.CharField(choices=[('sunny', 'Sunny'), ('partly_cloudy', 'Partly Cloudy'), ('cloudy', 'Cloudy'), ('rainy', 'Rainy'), ('extreme', 'Extreme')], default='partly_cloudy', max_length=32)),
                ('weather_temperature_c', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('weather_humidity_percent', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('weather_wind', models.CharField(blank=True, max_length=100)),
                ('workforce_count', models.PositiveIntegerField(default=0)),
                ('working_hours', models.DecimalField(decimal_places=1, default=8, max_digits=4)),
                ('work_description', models.TextField(blank=True)),
                ('progress_percent', models.PositiveSmallIntegerField(default=0)),
                ('milestones', models.JSONField(blank=True, default=list)),
                ('labour_activities', models.JSONField(blank=True, default=list)),
                ('equipment_used', models.JSONField(blank=True, default=list)),
                ('materials_consumed', models.JSONField(blank=True, default=list)),
                ('delays', models.TextField(blank=True)),
                ('safety_concerns', models.TextField(blank=True)),
                ('required_actions', models.TextField(blank=True)),
                ('site_conditions_notes', models.TextField(blank=True)),
                ('photos', models.JSONField(blank=True, default=list)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('action_owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_diary_actions', to=settings.AUTH_USER_MODEL)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_diary_entries', to=settings.AUTH_USER_MODEL)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diary_entries', to='companies.company')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_diary_entries', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diary_entries', to='projects.project')),
                ('supervisor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supervised_diary_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-entry_date', '-created_at'],
                'indexes': [models.Index(fields=['company', 'project', 'entry_date'], name='diary_sited_company_bd5e8a_idx'), models.Index(fields=['company', 'status'], name='diary_sited_company_6a2e33_idx')],
                'unique_together': {('project', 'entry_date')},
            },
        ),
    ]
