# Generated by Django 6.0.7 on 2026-07-08 20:12

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0003_teaminvitation'),
        ('projects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LibraryItem',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('asset_type', models.CharField(choices=[('document', 'Document'), ('photo', 'Photo')], default='document', max_length=16)),
                ('document_type', models.CharField(choices=[('drawing', 'Drawing'), ('contract', 'Contract'), ('report', 'Report'), ('inspection', 'Inspection'), ('receipt', 'Receipt'), ('other', 'Other')], default='other', max_length=32)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('folder_path', models.CharField(blank=True, max_length=255)),
                ('file_url', models.URLField(blank=True)),
                ('file_extension', models.CharField(blank=True, max_length=20)),
                ('mime_type', models.CharField(blank=True, max_length=100)),
                ('size_bytes', models.PositiveBigIntegerField(default=0)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('captured_at', models.DateTimeField(blank=True, null=True)),
                ('is_archived', models.BooleanField(default=False)),
                ('version_number', models.PositiveIntegerField(default=1)),
                ('is_current_version', models.BooleanField(default=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='library_items', to='companies.company')),
                ('parent_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='versions', to='documents.libraryitem')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='library_items', to='projects.project')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_library_items', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['company', 'asset_type', 'is_archived'], name='documents_l_company_bff7e0_idx'), models.Index(fields=['company', 'document_type'], name='documents_l_company_ed36f8_idx'), models.Index(fields=['project', 'asset_type'], name='documents_l_project_f53bef_idx'), models.Index(fields=['company', 'folder_path'], name='documents_l_company_3582cf_idx')],
            },
        ),
    ]
