# Generated by Django 6.0.7 on 2026-07-08 20:40

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0003_teaminvitation'),
        ('projects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GeneratedReport',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('report_type', models.CharField(choices=[('progress', 'Progress Report'), ('cost_variance', 'Cost Variance Report'), ('attendance_payroll', 'Attendance Payroll Export'), ('material_usage', 'Material Usage Report'), ('diary_summary', 'Diary Summary PDF'), ('budget_vs_actual', 'Budget vs Actual'), ('safety_incidents', 'Safety Incidents'), ('custom', 'Custom Report Builder')], db_index=True, max_length=32)),
                ('title', models.CharField(max_length=255)),
                ('date_from', models.DateField(blank=True, null=True)),
                ('date_to', models.DateField(blank=True, null=True)),
                ('output_format', models.CharField(default='json', max_length=16)),
                ('status', models.CharField(default='ready', max_length=16)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generated_reports', to='companies.company')),
                ('generated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_reports', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_reports', to='projects.project')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['company', 'report_type'], name='reports_gen_company_2a701c_idx'), models.Index(fields=['company', 'created_at'], name='reports_gen_company_372121_idx'), models.Index(fields=['project', 'created_at'], name='reports_gen_project_49e77f_idx')],
            },
        ),
    ]
